import { useState, useCallback, useRef } from 'react';
import { CONFIG } from '../config';

export interface ColumnInfo {
  name: string;
  type: string;
  nullable: boolean;
  primary_key: boolean;
}

interface CacheEntry<T> {
  data: T;
  timestamp: number;
}

const CACHE_TTL = 5 * 60 * 1000; // 5 minutes

class CacheFactory {
  private cache = new Map<string, CacheEntry<any>>();

  get<T>(key: string): T | null {
    const entry = this.cache.get(key);
    if (!entry) return null;

    if (Date.now() - entry.timestamp > CACHE_TTL) {
      this.cache.delete(key);
      return null;
    }

    return entry.data;
  }

  set<T>(key: string, data: T): void {
    this.cache.set(key, { data, timestamp: Date.now() });
  }

  invalidate(key: string): void {
    this.cache.delete(key);
  }

  clear(): void {
    this.cache.clear();
  }
}

const cacheFactory = new CacheFactory();

export function useDashboard() {
  const [tables, setTables] = useState<string[]>([]);
  const [selectedTable, setSelectedTable] = useState<string>('');
  const [columns, setColumns] = useState<ColumnInfo[]>([]);
  const [rows, setRows] = useState<any[]>([]);
  const [formData, setFormData] = useState<Record<string, string>>({});
  const [errorMessage, setErrorMessage] = useState<string>('');
  const [editingPkValue, setEditingPkValue] = useState<string | null>(null);

  const [isLoadingTables, setIsLoadingTables] = useState(false);
  const [isLoadingColumns, setIsLoadingColumns] = useState(false);
  const [isLoadingRows, setIsLoadingRows] = useState(false);
  const [isSubmitting, setIsSubmitting] = useState(false);

  const [jsonEditorOpen, setJsonEditorOpen] = useState(false);
  const [jsonEditorField, setJsonEditorField] = useState('');
  const jsonEditorValueRef = useRef('');

  const apiUrl = CONFIG.API_URL;

  const loadTables = useCallback(async () => {
    const cached = cacheFactory.get<string[]>('tables');
    if (cached) {
      setTables(cached);
      return;
    }

    setIsLoadingTables(true);
    try {
      const response = await fetch(`${apiUrl}/admin/tables`);
      const result = await response.json();
      const data = result.data || result;
      setTables(Array.isArray(data) ? data : []);
      cacheFactory.set('tables', data);
    } catch (err) {
      setErrorMessage('Could not load tables - is backend-core running?');
    } finally {
      setIsLoadingTables(false);
    }
  }, [apiUrl]);

  const loadColumns = useCallback(
    async (table: string) => {
      const cacheKey = `columns:${table}`;
      const cached = cacheFactory.get<ColumnInfo[]>(cacheKey);
      if (cached) {
        setColumns(cached);
        return;
      }

      setIsLoadingColumns(true);
      try {
        const response = await fetch(`${apiUrl}/admin/tables/${table}/columns`);
        const result = await response.json();
        const data = result.data || result;
        setColumns(Array.isArray(data) ? data : []);
        cacheFactory.set(cacheKey, data);
      } catch (err) {
        setErrorMessage('Could not load columns');
      } finally {
        setIsLoadingColumns(false);
      }
    },
    [apiUrl]
  );

  const loadRows = useCallback(
    async (table: string) => {
      const cacheKey = `rows:${table}`;
      const cached = cacheFactory.get<any[]>(cacheKey);
      if (cached) {
        setRows(cached);
        return;
      }

      setIsLoadingRows(true);
      try {
        const response = await fetch(`${apiUrl}/admin/tables/${table}/rows`);
        const result = await response.json();
        const data = result.data || result;
        setRows(Array.isArray(data) ? data : []);
        cacheFactory.set(cacheKey, data);
      } catch (err) {
        setErrorMessage('Could not load rows');
      } finally {
        setIsLoadingRows(false);
      }
    },
    [apiUrl]
  );

  const selectTable = useCallback(
    (table: string) => {
      setSelectedTable(table);
      setFormData({});
      setEditingPkValue(null);
      setErrorMessage('');
      loadColumns(table);
      loadRows(table);
    },
    [loadColumns, loadRows]
  );

  const updateField = useCallback((column: string, value: string) => {
    setFormData((prev) => ({ ...prev, [column]: value }));
  }, []);

  const isAutoGenerated = (column: ColumnInfo): boolean => {
    const name = column.name.toLowerCase();
    return (
      column.primary_key ||
      name.includes('id') ||
      name.includes('embedding') ||
      name.includes('created_at') ||
      name.includes('updated_at') ||
      column.type.includes('vector')
    );
  };

  const shouldShowInForm = (column: ColumnInfo, isEditing: boolean): boolean => {
    if (isEditing) return true;
    return !isAutoGenerated(column);
  };

  const getColumnHint = (column: ColumnInfo): string => {
    const name = column.name.toLowerCase();
    if (column.primary_key || name.includes('id')) return '(auto-generated)';
    if (name.includes('embedding') || column.type.includes('vector')) return '(auto-generated)';
    if (name.includes('created_at')) return '(current time)';
    if (name.includes('updated_at')) return '(current time)';
    return '';
  };

  const isJsonb = (column: ColumnInfo): boolean => {
    return column.type.toLowerCase().includes('jsonb');
  };

  const isTimestamp = (column: ColumnInfo): boolean => {
    const type = column.type.toLowerCase();
    return type.includes('timestamp') || type.includes('datetime') || type.includes('date');
  };

  const getJsonbPlaceholder = (column: ColumnInfo): string => {
    const name = column.name.toLowerCase();
    if (name.includes('config') || name.includes('settings')) {
      return '{"key": "value"}';
    }
    if (name.includes('data') || name.includes('metadata')) {
      return '{"field": "value"}';
    }
    return '{}';
  };

  const pkColumn = columns.find((c) => c.primary_key)?.name;

  const startEdit = (row: any) => {
    if (!pkColumn) return;

    const data: Record<string, string> = {};
    for (const key of Object.keys(row)) {
      data[key] = row[key] === null || row[key] === undefined ? '' : String(row[key]);
    }
    setFormData(data);
    setEditingPkValue(row[pkColumn]);
    setErrorMessage('');
  };

  const cancelEdit = () => {
    setFormData({});
    setEditingPkValue(null);
    setErrorMessage('');
  };

  const convertFormData = (data: Record<string, string>): Record<string, any> => {
    const converted: Record<string, any> = {};
    const columnsMap = new Map(columns.map((c) => [c.name, c]));

    for (const key in data) {
      const column = columnsMap.get(key);
      let value: any = data[key];

      if (column && value !== '') {
        const type = column.type.toLowerCase();

        if (type.includes('boolean')) {
          value = value === 'true' || value === true;
        } else if (type.includes('int') || type.includes('numeric') || type.includes('float')) {
          value = value === '' ? null : Number(value);
        }
      }

      converted[key] = value;
    }

    return converted;
  };

  const submit = async () => {
    setErrorMessage('');
    setIsSubmitting(true);

    try {
      const convertedData = convertFormData(formData);
      const cacheKey = `rows:${selectedTable}`;

      if (editingPkValue !== null && pkColumn) {
        // Update row
        const response = await fetch(
          `${apiUrl}/admin/tables/${selectedTable}/rows/${pkColumn}/${editingPkValue}`,
          {
            method: 'PATCH',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ data: convertedData }),
          }
        );

        if (!response.ok) {
          const err = await response.json();
          throw new Error(err?.detail || 'Update failed');
        }

        cacheFactory.invalidate(cacheKey);
        cancelEdit();
        await loadRows(selectedTable);
      } else {
        // Insert row
        const cleaned: Record<string, any> = {};
        for (const key in convertedData) {
          if (convertedData[key] !== '' && convertedData[key] !== null) {
            cleaned[key] = convertedData[key];
          }
        }

        const response = await fetch(`${apiUrl}/admin/tables/${selectedTable}/rows`, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ data: cleaned }),
        });

        if (!response.ok) {
          const err = await response.json();
          throw new Error(err?.detail || 'Insert failed');
        }

        setFormData({});
        cacheFactory.invalidate(cacheKey);
        await loadRows(selectedTable);
      }
    } catch (err) {
      setErrorMessage(err instanceof Error ? err.message : 'Operation failed');
    } finally {
      setIsSubmitting(false);
    }
  };

  const deleteRow = async (row: any) => {
    if (!pkColumn) return;

    setIsSubmitting(true);
    try {
      const response = await fetch(
        `${apiUrl}/admin/tables/${selectedTable}/rows/${pkColumn}/${row[pkColumn]}`,
        { method: 'DELETE' }
      );

      if (!response.ok) {
        throw new Error('Delete failed');
      }

      const cacheKey = `rows:${selectedTable}`;
      cacheFactory.invalidate(cacheKey);
      await loadRows(selectedTable);
    } catch (err) {
      setErrorMessage(err instanceof Error ? err.message : 'Delete failed');
    } finally {
      setIsSubmitting(false);
    }
  };

  const refreshTable = () => {
    cacheFactory.invalidate(`rows:${selectedTable}`);
    loadRows(selectedTable);
  };

  const openJsonEditor = (fieldName: string) => {
    setJsonEditorField(fieldName);
    jsonEditorValueRef.current = formData[fieldName] || '';
    setJsonEditorOpen(true);
  };

  const closeJsonEditor = () => {
    setJsonEditorOpen(false);
    jsonEditorValueRef.current = '';
    setJsonEditorField('');
  };

  const saveJsonEditor = () => {
    updateField(jsonEditorField, jsonEditorValueRef.current);
    closeJsonEditor();
  };

  return {
    // State
    tables,
    selectedTable,
    columns,
    rows,
    formData,
    errorMessage,
    editingPkValue,
    isLoadingTables,
    isLoadingColumns,
    isLoadingRows,
    isSubmitting,
    jsonEditorOpen,
    jsonEditorField,
    jsonEditorValueRef,
    pkColumn,

    // Methods
    loadTables,
    selectTable,
    updateField,
    isAutoGenerated,
    shouldShowInForm,
    getColumnHint,
    isJsonb,
    isTimestamp,
    getJsonbPlaceholder,
    startEdit,
    cancelEdit,
    submit,
    deleteRow,
    refreshTable,
    openJsonEditor,
    closeJsonEditor,
    saveJsonEditor,
  };
}
