import { useEffect, useMemo, memo, useCallback } from 'react';
import { useDashboard } from '../hooks/useDashboard';
import '../styles/dashboard.css';

const LoadingSpinner = memo(() => <div className="spinner"></div>);
const SmallSpinner = memo(() => <div className="spinner small"></div>);

const TableRow = memo(({ row, pkColumn, columns, onEdit, onDelete }: any) => (
  <tr key={pkColumn ? row[pkColumn] : Math.random()}>
    {Object.keys(row).map((key) => (
      <td key={key}>
        <div className="cell">{row[key]}</div>
      </td>
    ))}
    <td className="row-actions">
      <button className="btn-edit" onClick={() => onEdit(row)}>
        Edit
      </button>
      <button className="btn-delete" onClick={() => onDelete(row)}>
        Delete
      </button>
    </td>
  </tr>
));

function Dashboard() {
  const dashboard = useDashboard();

  useEffect(() => {
    dashboard.loadTables();
  }, [dashboard.loadTables]);

  return (
    <div className="dashboard">
      {/* Sidebar */}
      <aside className="sidebar">
        <h2>Tables</h2>
        {dashboard.isLoadingTables ? (
          <div className="loading-overlay">
            <LoadingSpinner />
          </div>
        ) : (
          dashboard.tables.map((table) => (
            <button
              key={table}
              className={`table-btn ${table === dashboard.selectedTable ? 'active' : ''}`}
              onClick={() => dashboard.selectTable(table)}
            >
              {table}
            </button>
          ))
        )}
      </aside>

      {/* Main Content */}
      <main className="content">
        {dashboard.errorMessage && (
          <div className="error">{dashboard.errorMessage}</div>
        )}

        {!dashboard.selectedTable && (
          <div className="empty">Select a table to view and insert data.</div>
        )}

        {dashboard.selectedTable && (
          <div>
            <div style={{ display: 'flex', alignItems: 'center', gap: '12px', marginBottom: '16px' }}>
              <h2 style={{ margin: 0 }}>{dashboard.selectedTable}</h2>
              <button type="button" className="btn-refresh" onClick={() => dashboard.refreshTable()}>
                Refresh
              </button>
            </div>

            {/* Insert/Edit Form */}
            <form
              className={`insert-form ${dashboard.isLoadingColumns || dashboard.isSubmitting ? 'loading' : ''}`}
              onSubmit={(e) => {
                e.preventDefault();
                dashboard.submit();
              }}
            >
              {dashboard.isLoadingColumns ? (
                <div className="form-loading">
                  <LoadingSpinner />
                  <span>Loading fields...</span>
                </div>
              ) : (
                <>
                  {dashboard.columns.map((col) => {
                    if (!dashboard.shouldShowInForm(col, dashboard.editingPkValue !== null)) {
                      return null;
                    }

                    const isAutoGen = dashboard.isAutoGenerated(col);
                    const isEditing = dashboard.editingPkValue !== null;

                    return (
                      <div
                        key={col.name}
                        className={`field ${isAutoGen && !isEditing ? 'auto-gen' : ''}`}
                      >
                        <label>
                          {col.name}
                          <span className="type">{col.type}</span>
                          {dashboard.getColumnHint(col) && (
                            <span className="hint">{dashboard.getColumnHint(col)}</span>
                          )}
                          {col.primary_key && <span className="pk">PK</span>}
                        </label>

                        {dashboard.isJsonb(col) ? (
                          <div className="jsonb-input-group">
                            <input
                              type="text"
                              value={
                                (dashboard.formData[col.name] || '').substring(0, 50) +
                                (dashboard.formData[col.name]?.length > 50 ? '...' : '')
                              }
                              readOnly
                              placeholder={dashboard.getJsonbPlaceholder(col)}
                              className="jsonb-preview"
                            />
                            <button
                              type="button"
                              className="btn-edit-json"
                              onClick={() => dashboard.openJsonEditor(col.name)}
                              title="Edit JSON"
                            >
                              ✎
                            </button>
                          </div>
                        ) : dashboard.isTimestamp(col) ? (
                          <input
                            type="datetime-local"
                            value={dashboard.formData[col.name] || ''}
                            onChange={(e) => dashboard.updateField(col.name, e.target.value)}
                            disabled={isEditing && col.primary_key}
                            readOnly={isAutoGen && !isEditing}
                            name={col.name}
                          />
                        ) : (
                          <input
                            type="text"
                            value={dashboard.formData[col.name] || ''}
                            onChange={(e) => dashboard.updateField(col.name, e.target.value)}
                            disabled={isEditing && col.primary_key}
                            readOnly={isAutoGen && !isEditing}
                            name={col.name}
                            placeholder={isAutoGen ? 'Auto-generated' : ''}
                          />
                        )}
                      </div>
                    );
                  })}

                  <button type="submit" className="btn-insert" disabled={dashboard.isLoadingColumns || dashboard.isSubmitting}>
                    {dashboard.isSubmitting ? (
                      <>
                        <SmallSpinner />
                        {dashboard.editingPkValue !== null ? 'Saving...' : 'Inserting...'}
                      </>
                    ) : (
                      <>{dashboard.editingPkValue !== null ? 'Save Changes' : 'Insert Row'}</>
                    )}
                  </button>

                  {dashboard.editingPkValue !== null && (
                    <button type="button" className="btn-cancel" onClick={() => dashboard.cancelEdit()}>
                      Cancel
                    </button>
                  )}
                </>
              )}
            </form>

            {/* JSON Editor Modal */}
            {dashboard.jsonEditorOpen && (
              <div className="modal-overlay" onClick={() => dashboard.closeJsonEditor()}>
                <div className="modal-content" onClick={(e) => e.stopPropagation()}>
                  <div className="modal-header">
                    <h3>Edit {dashboard.jsonEditorField}</h3>
                    <button type="button" className="btn-close" onClick={() => dashboard.closeJsonEditor()}>
                      ✕
                    </button>
                  </div>
                  <textarea
                    className="json-editor"
                    value={dashboard.jsonEditorValueRef.current}
                    onChange={(e) => {
                      dashboard.jsonEditorValueRef.current = e.target.value;
                    }}
                    placeholder='{"key": "value"}'
                  />
                  <div className="modal-footer">
                    <button type="button" className="btn-cancel" onClick={() => dashboard.closeJsonEditor()}>
                      Cancel
                    </button>
                    <button type="button" className="btn-save-json" onClick={() => dashboard.saveJsonEditor()}>
                      Save
                    </button>
                  </div>
                </div>
              </div>
            )}

            {/* Rows Table */}
            {dashboard.isLoadingRows ? (
              <div className="table-scroll">
                <table className="rows-table">
                  <thead>
                    <tr>
                      {dashboard.columns.map((col) => (
                        <th key={col.name}>{col.name}</th>
                      ))}
                      <th></th>
                    </tr>
                  </thead>
                  <tbody>
                    {[0, 1, 2, 3, 4, 5].map((i) => (
                      <tr key={i} className="skeleton-row">
                        {dashboard.columns.map((col) => (
                          <td key={col.name}>
                            <div className="skeleton-cell"></div>
                          </td>
                        ))}
                        <td>
                          <div className="skeleton-actions"></div>
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            ) : dashboard.rows.length > 0 ? (
              <div className="table-scroll">
                <table className="rows-table">
                  <thead>
                    <tr>
                      {Object.keys(dashboard.rows[0]).map((key) => (
                        <th key={key}>{key}</th>
                      ))}
                      <th></th>
                    </tr>
                  </thead>
                  <tbody>
                    {dashboard.rows.map((row, idx) => (
                      <TableRow
                        key={dashboard.pkColumn ? row[dashboard.pkColumn] : idx}
                        row={row}
                        pkColumn={dashboard.pkColumn}
                        columns={dashboard.columns}
                        onEdit={dashboard.startEdit}
                        onDelete={dashboard.deleteRow}
                      />
                    ))}
                  </tbody>
                </table>
              </div>
            ) : (
              <div className="empty">No rows yet.</div>
            )}
          </div>
        )}
      </main>
    </div>
  );
}

export default memo(Dashboard);
