import { Component, computed, inject, signal, OnInit } from '@angular/core';
import { AdminService, ColumnInfo } from '../admin.service';

@Component({
  selector: 'app-dashboard',
  templateUrl: './dashboard.component.html',
  styleUrls: ['./dashboard.component.css']
})
export class DashboardComponent implements OnInit {
  private readonly adminService = inject(AdminService);

  protected readonly tables = signal<string[]>([]);
  protected readonly selectedTable = signal<string>('');
  protected readonly columns = signal<ColumnInfo[]>([]);
  protected readonly rows = signal<any[]>([]);
  protected readonly formData = signal<Record<string, string>>({});
  protected readonly errorMessage = signal<string>('');
  protected readonly editingPkValue = signal<string | null>(null);

  protected readonly isLoadingTables = signal(false);
  protected readonly isLoadingColumns = signal(false);
  protected readonly isLoadingRows = signal(false);
  protected readonly isSubmitting = signal(false);

  protected readonly jsonEditorOpen = signal(false);
  protected readonly jsonEditorField = signal('');
  protected jsonEditorValue = '';

  protected readonly pkColumn = computed(() => this.columns().find((c) => c.primary_key)?.name);

  ngOnInit() {
    this.loadTables();
  }

  private loadTables() {
    this.isLoadingTables.set(true);
    this.adminService.getTables().subscribe({
      next: (res) => this.tables.set(res.data || []),
      error: () => this.errorMessage.set('Could not load tables - is backend-core running?'),
      complete: () => this.isLoadingTables.set(false)
    });
  }

  protected selectTable(table: string) {
    this.selectedTable.set(table);
    this.formData.set({});
    this.editingPkValue.set(null);
    this.errorMessage.set('');

    this.isLoadingColumns.set(true);
    this.adminService.getColumns(table).subscribe({
      next: (res) => this.columns.set(res.data || []),
      complete: () => this.isLoadingColumns.set(false)
    });
    this.loadRows();
  }

  private loadRows() {
    if (!this.selectedTable()) return;
    this.isLoadingRows.set(true);
    this.adminService.getRows(this.selectedTable()).subscribe({
      next: (res) => this.rows.set(res.data || []),
      error: () => this.errorMessage.set('Could not load rows'),
      complete: () => this.isLoadingRows.set(false)
    });
  }

  protected updateField(column: string, value: string) {
    this.formData.update((data) => ({ ...data, [column]: value }));
  }

  protected isAutoGenerated(column: ColumnInfo): boolean {
    const name = column.name.toLowerCase();
    return (
      column.primary_key ||
      name.includes('id') ||
      name.includes('embedding') ||
      name.includes('created_at') ||
      name.includes('updated_at') ||
      column.type.includes('vector')
    );
  }

  protected shouldShowInForm(column: ColumnInfo, isEditing: boolean): boolean {
    if (isEditing) return true;
    return !this.isAutoGenerated(column);
  }

  protected getColumnHint(column: ColumnInfo): string {
    const name = column.name.toLowerCase();
    if (column.primary_key || name.includes('id')) return '(auto-generated)';
    if (name.includes('embedding') || column.type.includes('vector')) return '(auto-generated)';
    if (name.includes('created_at')) return '(current time)';
    if (name.includes('updated_at')) return '(current time)';
    return '';
  }

  protected isJsonb(column: ColumnInfo): boolean {
    return column.type.toLowerCase().includes('jsonb');
  }

  protected isTimestamp(column: ColumnInfo): boolean {
    const type = column.type.toLowerCase();
    return type.includes('timestamp') || type.includes('datetime') || type.includes('date');
  }

  protected getJsonbPlaceholder(column: ColumnInfo): string {
    const name = column.name.toLowerCase();
    if (name.includes('config') || name.includes('settings')) {
      return '{"key": "value"}';
    }
    if (name.includes('data') || name.includes('metadata')) {
      return '{"field": "value"}';
    }
    return '{}';
  }

  protected startEdit(row: any) {
    const pkColumn = this.pkColumn();
    if (!pkColumn) return;

    const data: Record<string, string> = {};
    for (const key of this.rowColumns(row)) {
      data[key] = row[key] === null || row[key] === undefined ? '' : String(row[key]);
    }
    this.formData.set(data);
    this.editingPkValue.set(row[pkColumn]);
    this.errorMessage.set('');
  }

  protected cancelEdit() {
    this.formData.set({});
    this.editingPkValue.set(null);
    this.errorMessage.set('');
  }

  protected submit() {
    this.errorMessage.set('');
    this.isSubmitting.set(true);
    const data = this.formData();
    const convertedData = this.convertFormData(data);
    const editingPk = this.editingPkValue();
    const pkColumn = this.pkColumn();

    if (editingPk !== null && pkColumn) {
      this.adminService.updateRow(this.selectedTable(), pkColumn, editingPk, convertedData).subscribe({
        next: () => {
          this.cancelEdit();
          this.loadRows();
        },
        error: (err) => this.errorMessage.set(err?.error?.detail || 'Update failed'),
        complete: () => this.isSubmitting.set(false)
      });
      return;
    }

    const cleaned: Record<string, any> = {};
    for (const key in convertedData) {
      if (convertedData[key] !== '' && convertedData[key] !== null) {
        cleaned[key] = convertedData[key];
      }
    }

    this.adminService.insertRow(this.selectedTable(), cleaned).subscribe({
      next: () => {
        this.formData.set({});
        this.loadRows();
      },
      error: (err) => this.errorMessage.set(err?.error?.detail || 'Insert failed'),
      complete: () => this.isSubmitting.set(false)
    });
  }

  private convertFormData(data: Record<string, string>): Record<string, any> {
    const converted: Record<string, any> = {};
    const columnsMap = new Map(this.columns().map(c => [c.name, c]));

    for (const key in data) {
      const column = columnsMap.get(key);
      let value: any = data[key];

      if (column && value !== '') {
        const type = column.type.toLowerCase();

        if (type.includes('boolean')) {
          value = value === 'true' || value === true;
        } else if (type.includes('int') || type.includes('numeric') || type.includes('float')) {
          value = value === '' ? null : Number(value);
        }
      }

      converted[key] = value;
    }

    return converted;
  }

  protected deleteRow(row: any) {
    const pkColumn = this.pkColumn();
    if (!pkColumn) return;

    this.isSubmitting.set(true);
    this.adminService.deleteRow(this.selectedTable(), pkColumn, row[pkColumn]).subscribe({
      next: () => this.loadRows(),
      error: () => this.errorMessage.set('Delete failed'),
      complete: () => this.isSubmitting.set(false)
    });
  }

  protected rowColumns(row: any): string[] {
    return Object.keys(row);
  }

  protected refreshTable() {
    this.adminService.clearCache(this.selectedTable());
    this.loadRows();
  }

  protected openJsonEditor(fieldName: string) {
    this.jsonEditorField.set(fieldName);
    this.jsonEditorValue = this.formData()[fieldName] || '';
    this.jsonEditorOpen.set(true);
  }

  protected closeJsonEditor() {
    this.jsonEditorOpen.set(false);
    this.jsonEditorValue = '';
    this.jsonEditorField.set('');
  }

  protected saveJsonEditor() {
    const fieldName = this.jsonEditorField();
    this.updateField(fieldName, this.jsonEditorValue);
    this.closeJsonEditor();
  }
}
